# -*- coding: utf-8 -*-
"""Task1_Language_Translation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ipNVTvxLY0Dq1Kij3XDIDS3owM9j5qqw
"""

# Install required libraries
!pip install googletrans==4.0.0-rc1
!pip install gtts
!pip install ipywidgets

# Import libraries
from googletrans import Translator, LANGUAGES
from gtts import gTTS
from IPython.display import display, Audio, Javascript
import ipywidgets as widgets
import os

# Translator object
translator = Translator()

# Language dictionary (Google supported languages)
languages = {name.title(): code for code, name in LANGUAGES.items()}
sorted_languages = sorted(languages.keys())

# Reverse mapping for detection display
code_to_language = {code: name.title() for code, name in LANGUAGES.items()}

# Text input box
text_input = widgets.Textarea(
    placeholder='Enter text here...',
    description='Text:',
    layout=widgets.Layout(width='650px', height='120px')
)

# Language dropdowns
language_options = ['Auto Detect'] + sorted_languages

source_lang = widgets.Dropdown(
    options=language_options,
    value='Auto Detect',
    description='Source Language:'
)

target_lang = widgets.Dropdown(
    options=['Select a language...'] + sorted_languages,
    value='Select a language...',
    description='Translated Language:'
)

# Buttons
translate_button = widgets.Button(description='Translate', button_style='success')
copy_button = widgets.Button(description='Copy Text', button_style='info')
speak_button = widgets.Button(description='Speak', button_style='warning')
clear_button = widgets.Button(description='Clear', button_style='danger')

# Output area
output_area = widgets.Output()

# Global storage
translated_text_global = ""
detected_language_global = ""

# Translation function
def translate_text(b):

    global translated_text_global
    global detected_language_global

    output_area.clear_output()

    text = text_input.value.strip()

    if text == "":
        with output_area:
            print("Please enter some text.")
        return

    if len(text) < 2:
        with output_area:
            print("Text is too short to translate.")
        return

    if target_lang.value == "Select a language...":
        with output_area:
            print("Please select a target language.")
        return

    try:
        # Detect language
        if source_lang.value == "Auto Detect":
            detected = translator.detect(text)
            src = detected.lang
            detected_language_global = code_to_language.get(src, "Unknown")
        else:
            src = languages[source_lang.value]
            detected_language_global = source_lang.value

        dest = languages[target_lang.value]

        if src == dest:
            with output_area:
                print("Source and target language cannot be same.")
            return

        # Translate
        translated = translator.translate(text, src=src, dest=dest)
        translated_text_global = translated.text

        with output_area:
            print("Translation Successful\n")
            print("Detected Language:", detected_language_global)
            print("Source Language:", source_lang.value)
            print("Translated Language:", target_lang.value)
            print("\nTranslated Text:\n")
            print(translated.text)

    except ConnectionError:
        with output_area:
            print("Internet connection error.")

    except Exception as e:
        with output_area:
            print("Translation failed.")
            print(str(e))

def copy_text(b):

    global translated_text_global

    if translated_text_global == "":
        with output_area:
            print("No translated text available.")
        return

    js_code = f"""
    navigator.clipboard.writeText(`{translated_text_global}`);
    alert('Copied successfully');
    """

    display(Javascript(js_code))

def speak_text(b):

    global translated_text_global

    if translated_text_global == "":
        with output_area:
            print("No translated text available.")
        return

    try:
        lang_code = languages[target_lang.value]

        if os.path.exists("audio.mp3"):
            os.remove("audio.mp3")

        tts = gTTS(text=translated_text_global, lang=lang_code, slow=False)
        tts.save("audio.mp3")

        output_area.clear_output(wait=True)

        with output_area:
            display(Audio("audio.mp3", autoplay=True))

    except Exception as e:
        with output_area:
            print("Text-to-speech failed.")
            print(str(e))

# Clear function
def clear_output_function(b):

    global translated_text_global

    translated_text_global = ""
    text_input.value = ""
    output_area.clear_output()

    with output_area:
        print("Cleared successfully.")

# Button events
translate_button.on_click(translate_text)
copy_button.on_click(copy_text)
speak_button.on_click(speak_text)
clear_button.on_click(clear_output_function)

# UI display
display(text_input)
display(source_lang)
display(target_lang)

display(
    widgets.HBox([
        translate_button,
        copy_button,
        speak_button,
        clear_button
    ])
)

display(output_area)